"""empty message

Revision ID: 3c1e90fd03d7
Revises: 7ae8fd1d039e
Create Date: 2021-01-09 01:02:26.936177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c1e90fd03d7'
down_revision = '7ae8fd1d039e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.String(length=140), nullable=True))
    op.drop_column('post', 'post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('post', 'body')
    # ### end Alembic commands ###
