"""followers

Revision ID: 48142eace5e9
Revises: 35210590dc5d
Create Date: 2021-02-05 23:11:45.811057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48142eace5e9'
down_revision = '35210590dc5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
